name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Récupération du code source
      - uses: actions/checkout@v3

      # Configuration de la version de Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      # Lancement du linter flake8
      - name: Lint with flake8
        run: |
          flake8 .

      # Exécution des tests avec pytest
      - name: Test with pytest
        run: |
          pytest